"""Loaders for the curated worst-case suite.

Synthetic cases come from ``data/dvfs/canonical_2tri_2d/*.npz`` (already
generated by ``scripts/_save_canonical_2tri_2d.py``). B0039 slices come
from the real registration DVF.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from dvfopt.jacobian.triangle_sign import _triangle_areas_2d

_REPO = Path(__file__).resolve().parents[3]
_CANONICAL_DIR = _REPO / 'data' / 'dvfs' / 'canonical_2tri_2d'
_B0039 = _REPO / 'data' / 'dvfs' / 'b0039' / 'b0039_laplacian_deformation_field.npy'
_ADVERSARIAL_DIR = Path(__file__).parent / 'synthetic'


def _stats(phi_2hw: np.ndarray) -> dict:
    """Compute initial 2-tri fold count + min_T."""
    T1, T2 = _triangle_areas_2d(phi_2hw[0], phi_2hw[1])
    return {
        'init_n_neg': int((np.minimum(T1, T2) <= 0).sum()),
        'init_min_T': float(np.minimum(T1, T2).min()),
        'shape': tuple(phi_2hw.shape[1:]),
    }


def load_synthetic_canonical():
    """Yield ``(name, phi_2hw, meta)`` for every NPZ in
    ``data/dvfs/canonical_2tri_2d/`` and the local adversarial
    ``synthetic/`` directory."""
    out = []
    for d in (_CANONICAL_DIR, _ADVERSARIAL_DIR):
        if not d.exists():
            continue
        for path in sorted(d.glob('*.npz')):
            with np.load(path, allow_pickle=False) as data:
                phi = data['phi'].astype(np.float64)
            out.append((path.stem, phi, _stats(phi)))
    return out


def load_b0039_slice(z: int):
    """Load B0039 z-slice as ``(name, phi_2hw, meta)``."""
    vol = np.load(_B0039)
    D = vol.shape[1]
    if not (0 <= z < D):
        raise IndexError(f'z={z} out of [0, {D})')
    phi = vol[1:, z].astype(np.float64)
    name = f'b0039_z{z:03d}'
    return name, phi, _stats(phi)
